# -*- coding: utf-8 -*-
"""Python Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mliPgjZZa2QIV9RWjWr0gWMrMlagI5xK
"""

lst=[1,2,3,12,18,20]
max(lst)

len(lst)

print(lst.pop(3))

lst1= [2009, 'manni',12,11];
lst2=[1234,7893];
lst1.extend(lst2)
print ("Extended List : ", lst1)

lst3=["Hi","Good Evening","One","And","All"]
lst3.reverse();
print(lst3)

